version: '3.3'
services:
    application:
        build:
            context: php
            dockerfile: Dockerfile
        container_name: application-hexa
        hostname: application-hexa
        restart: always
        volumes:
            - ./:/var/www/html/
        ports:
            - "80:80"
        networks:
            - bot-network

    database:
        image: mysql:5.7
        container_name: hexa-database
        hostname: hexa-database
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'HFOktgcngMYqXKH#'
            MYSQL_ROOT_HOST: '%'
            MYSQL_LOG_CONSOLE: '1'
            MYSQL_DATABASE: 'hexa'
            MYSQL_USER: 'carlos'
            MYSQL_PASSWORD: 'HFOktgcngMYqXKH#'
            TZ: 'America/Sao_Paulo'
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - bot-network
    
    redis:
        image: redis:latest
        container_name: hexa_redis
        restart: always
        ports:
        - "6379:6379"
        networks:
        - bot-network

volumes:
    db-data:

networks:
    bot-network:
        driver: bridge